#!/bin/bash
#for each id in the cleaned link file download its link using wget
#and sleep for random time(0.1-0.9 seconds)

for ID in $(<crawledmenus.crawl.cleaned)
   do 
      wget -nc -P ./harvestedmenus/ "http://openmenu.com/menu/${ID}"
      sleep .$[ ( $RANDOM % 10 ) + 1 ]s
   done
